name: Deploy static content to Pages

on:
  push:
    branches: ["gh-pages"]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Dependencies
        run: npm install

      - name: Build and Deploy
        run: |
          npm run build
          npm install gh-pages --save-dev
          npx gh-pages -d build
